### ISSUE TITLE
WIN10 EE get error 0x8007000D for mingw32/64 vlmcsd  ,BUT working good in linux vlmcsd .

### ISSUE THREAD

**Issue by 90999** [Wind4/vlmcsd#9] opened 2017-09-08 10:59 UTC
ubuntu64 17XX ,
all  the gcc version are  6.3  , vlmcs -l 11  127.0.01
when  " make CC=gcc/arm-linux-**/mipsel-linux-**  " , run vlmcsd  ,  WIN10 EE  not any error !!
Sending activation request (KMS V6) 1 of 1  -> 03612-00206-507-155388-03-2067-14393.0000-2512016 (3A1C049600B60076)
when   " make CC=**-w64-mingw32-gcc  "  , run vlmcsd  ,  WIN10 EE   say 0x8007000D error 
Sending activation request (KMS V6) 1 of 1  -> 03612-00206-503-210187-03-3081-14393.0000-0022017 (3A1C049600B60076)

:D , Very insteresting  !

**Comment by rouben** [comment] 2017-09-08 15:16
Are you running vomcsd on the same Windows 10 computer that you’re trying to activate? If yes, then this is a duplicate of issue #6 (see last 2 comments).

**Closed** 2017-10-17 02:40 UTC
