### ISSUE TITLE
logfile in vlmcsd.ini is not working

### ISSUE THREAD

**Issue by tbsky** [Wind4/vlmcsd#35] opened 2020-01-12 12:08 UTC
hi:
   I tried  vlmcsd  version svn1112.
   vlmcsd -l /var/log/vlmscd.log -D  => it works fine.
   vlmcsd -i /etc/vlmcsd/vlmcsd.ini -D ( "logfile =/var/log/vlmcsd.log"  defined at vlmcsd.ini)  => not working. there is nothing in the log file.

   other parameter like "logverbose = true" defined at vlmcsd.ini is working fine. but "logfile" is not.

**Comment by tbsky** [comment] 2020-01-13 15:01
hi:
   ok I found the problem is caused by the default vlmcsd.ini dos line feed format. so it's duplicate of previous bugs.

**Comment by rouben** [comment] 2020-01-13 17:57
Yes, this is a duplicate of issue #22. I'll therefore close this issue.

**Closed by rouben** 2020-01-13 17:57 UTC
