### ISSUE TITLE
The Software Licensing Service reported that the product SKU is not found

### ISSUE THREAD

**Issue by zjcnew** [Wind4/vlmcsd#20] opened 2018-09-20 03:26 UTC
When I activate office2016, I type "cscript ospp.vbs /inpkey:XQNVK-8JYDB-WJ9W3-YJ8YR-WFG99",Prompt message:

Microsoft (R) Windows Script Host Version 5.812
版权所有(C) Microsoft Corporation。保留所有权利。

---Processing--------------------------
---------------------------------------
ERROR CODE: 0xC004F069
ERROR DESCRIPTION: The Software Licensing Service reported that the product SKU is not found.
---------------------------------------
---Exiting-----------------------------

**Comment by thirdwheel** [comment] 2018-09-20 03:43
I've sen this happen.  It's not a bug in vlmcsd, it's an issue with Office.

Likely what's going on is that the volume licensing SKUs are not installed on your system, but the retail ones are.  Have a look in the "C:\Program Files\Microsoft Office" folder for a "root" folder.  Digging deeper, you should find a Licenses16 folder and in that folder should be a bunch of XRM-MS files.  If so, this batch file will install the license certificates that you need, assuming they're all in place:

	@echo off
	:ADMIN
	openfiles >nul 2>nul ||(
	echo CreateObject^("Shell.Application"^).ShellExecute "%~s0", "", "", "runas", 1 >> "%temp%\getadmin.vbs"
	"%temp%\getadmin.vbs" >nul 2>&1
	goto:eof
	)
	del /f /q "%temp%\getadmin.vbs" >nul 2>nul

	for /f "tokens=6 delims=[]. " %%G in ('ver') do set win=%%G

	setlocal

	set OPPKEY=XQNVK-8JYDB-WJ9W3-YJ8YR-WFG99
	set PPKEY=YG9NW-3K39V-2T3HJ-93F3Q-G83KT
	set VPKEY=PD3PC-RHNGV-FXJ29-8JK7D-RJRJK
	set S4BKEY=869NQ-FJ69K-466HW-QYCP2-DDBV6

	pushd "%~dp0"
	Title Office 2016 Retail to Volume License Converter

	SET OfficePath=%ProgramFiles%\Microsoft Office
	if not exist "%OfficePath%\root\Licenses16" SET OfficePath=%ProgramFiles(x86)%\Microsoft Office
	if not exist "%OfficePath%\root\Licenses16" (
		echo Could not find the license files for Office 2016!
		pause
		goto :eof
	)

	echo Press Enter to start VL-Conversion...
	echo.
	pause
	echo.
	cd /D "%SystemRoot%\System32"

	if %win% GEQ 9200 (
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\ProPlusVL_KMS_Client-ppd.xrm-ms"
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\ProPlusVL_KMS_Client-ul.xrm-ms"
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\ProPlusVL_KMS_Client-ul-oob.xrm-ms"

		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\ProjectProVL_KMS_Client-ppd.xrm-ms"
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\ProjectProVL_KMS_Client-ul-oob.xrm-ms"
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\ProjectProVL_KMS_Client-ul.xrm-ms"

		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\VisioProVL_KMS_Client-ppd.xrm-ms"
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\VisioProVL_KMS_Client-ul-oob.xrm-ms"
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\VisioProVL_KMS_Client-ul.xrm-ms"

		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\SkypeforBusinessVL_KMS_Client-ppd.xrm-ms"
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\SkypeforBusinessVL_KMS_Client-ul.xrm-ms"
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\SkypeforBusinessVL_KMS_Client-ul-oob.xrm-ms"

		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\client-issuance-bridge-office.xrm-ms
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\client-issuance-root.xrm-ms
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\client-issuance-root-bridge-test.xrm-ms
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\client-issuance-stil.xrm-ms
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\client-issuance-ul.xrm-ms
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\client-issuance-ul-oob.xrm-ms
		cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\pkeyconfig-office.xrm-ms
	)
	 if %win% LSS 9200 (
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\ProPlusVL_KMS_Client-ppd.xrm-ms"
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\ProPlusVL_KMS_Client-ul.xrm-ms"
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\ProPlusVL_KMS_Client-ul-oob.xrm-ms"

		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\ProjectProVL_KMS_Client-ppd.xrm-ms"
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\ProjectProVL_KMS_Client-ul-oob.xrm-ms"
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\ProjectProVL_KMS_Client-ul.xrm-ms"

		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\VisioProVL_KMS_Client-ppd.xrm-ms"
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\VisioProVL_KMS_Client-ul-oob.xrm-ms"
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\VisioProVL_KMS_Client-ul.xrm-ms"0

		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\SkypeforBusinessVL_KMS_Client-ppd.xrm-ms"
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\SkypeforBusinessVL_KMS_Client-ul.xrm-ms"
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\SkypeforBusinessVL_KMS_Client-ul-oob.xrm-ms"

		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-bridge-office.xrm-ms
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-root.xrm-ms
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-root-bridge-test.xrm-ms
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-stil.xrm-ms
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-ul.xrm-ms
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-ul-oob.xrm-ms
		cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\pkeyconfig-office.xrm-ms
	)

	for %%a in (%OPPKEY% %PPKEY% %VPKEY% %S4BKEY%) do cscript "%OfficePath%\Office16\ospp.vbs" /inpkey:%%a
	cscript "%OfficePath%\Office16\ospp.vbs" /act

	echo.
	echo Retail to Volume License conversion finished.
	echo.
	pause

If you don't find these files, or the above batch file fails, uninstall Office 2016 and use the Office 365 click-to-run installer, which will bring in those certificate files.

**Comment by rouben** [comment] 2018-10-19 00:42
Can this be closed?

**Comment by rouben** [comment] 2018-11-21 20:37
Closing, as [latest release](https://github.com/Wind4/vlmcsd/releases/latest) addresses this issue.

**Closed by rouben** 2018-11-21 20:37 UTC
Labels: question

**Comment by pengcheng789** [comment] 2019-02-10 14:29
@rouben Could you tell me how to install volume licensing SKUs for office 2019?

**Comment by maxchendt** [comment] 2019-07-17 12:38
I have one that works for office 2019. But I do NOT know why it works.
`cscript "%ProgramFiles(x86)%\Microsoft Office\Office16\ospp.vbs" /dstatus`
with the following output


> LICENSE NAME: Office 19, Office19ProPlus2019VL_KMS_Client_AE edition
LICENSE DESCRIPTION: Office 19, VOLUME_KMSCLIENT channel
BETA EXPIRATION: 1601-01-01
LICENSE STATUS:  ---LICENSED---
ERROR CODE: 0x4004F040 (for information purposes only as the status is licensed)
ERROR DESCRIPTION: The Software Licensing Service reported that the product was activated but the owner should verify the Product Use Rights.
REMAINING GRACE: 179 days  (259199 minute(s) before expiring)


install volume licensing SKUs for office 2019

```
@echo off
:ADMIN
openfiles >nul 2>nul ||(
echo CreateObject^("Shell.Application"^).ShellExecute "%~s0", "", "", "runas", 1 >> "%temp%\getadmin.vbs"
"%temp%\getadmin.vbs" >nul 2>&1
goto:eof
)
del /f /q "%temp%\getadmin.vbs" >nul 2>nul

for /f "tokens=6 delims=[]. " %%G in ('ver') do set win=%%G

setlocal

pushd "%~dp0"
Title Office 2019 Retail to Volume License Converter

rem	SET OfficePath=%ProgramFiles%\Microsoft Office
SET OfficePath=%ProgramFiles(x86)%\Microsoft Office
if not exist "%OfficePath%\root\Licenses16" SET OfficePath=%ProgramFiles(x86)%\Microsoft Office
if not exist "%OfficePath%\root\Licenses16" (
	echo Could not find the license files for Office 2019!
	pause
	goto :eof
)

echo Press Enter to start VL-Conversion...
echo.
pause
echo.
cd /D "%SystemRoot%\System32"

if %win% GEQ 9200 (
	cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\ProPlus2019VL_KMS_Client_AE-ppd.xrm-ms"
	cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\ProPlus2019VL_KMS_Client_AE-ul.xrm-ms"
	cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\ProPlus2019VL_KMS_Client_AE-ul-oob.xrm-ms"


	cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\client-issuance-bridge-office.xrm-ms
	cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\client-issuance-root.xrm-ms
	cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\client-issuance-root-bridge-test.xrm-ms
	cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\client-issuance-stil.xrm-ms
	cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\client-issuance-ul.xrm-ms
	cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\client-issuance-ul-oob.xrm-ms
	cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\pkeyconfig-office.xrm-ms
)
 if %win% LSS 9200 (
	cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\ProPlus2019VL_KMS_Client_AE-ppd.xrm-ms"
	cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\ProPlus2019VL_KMS_Client_AE-ul.xrm-ms"
	cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\ProPlus2019VL_KMS_Client_AE-ul-oob.xrm-ms"


	cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-bridge-office.xrm-ms
	cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-root.xrm-ms
	cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-root-bridge-test.xrm-ms
	cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-stil.xrm-ms
	cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-ul.xrm-ms
	cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-ul-oob.xrm-ms
	cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\pkeyconfig-office.xrm-ms
)

cscript "%OfficePath%\Office16\ospp.vbs" /inpkey:NMMKJ-6RK4F-KMJVX-8D9MJ-6MWKP
cscript "%OfficePath%\Office16\ospp.vbs" /act

echo.
echo Retail to Volume License conversion finished.
echo.
pause



```

**Comment by thirdwheel** [comment] 2019-08-06 00:12
> I have one that works for office 2019. But I do NOT know why it works.
> `cscript "%ProgramFiles(x86)%\Microsoft Office\Office16\ospp.vbs" /dstatus`
> with the following output
> 
> (snip)

Hey @maxchendt, if this is your work, nice work adapting this to Office 2019.  It works because doing volume activation requires the license key files that get installed - otherwise it'll attempt to activate it retail and won't accept the KMS/VL key.

Did Microsoft go one key for all in 2019, or is that just the key for the main Office suite?

**Comment by sundreamlyu** [comment] 2019-12-15 07:58
Hi all: try to download '[Office Deployment Tool](https://www.microsoft.com/en-us/download/details.aspx?id=49117)' and use customized [configuration ](https://config.office.com/deploymentsettings) to setup VOL version at the very first.

**Comment by Sven2609** [comment] 2021-04-07 07:50
Hello,

could you please tell me what these files are exactly for? 

`cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-bridge-office.xrm-ms
cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-root.xrm-ms
cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-root-bridge-test.xrm-ms
cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-stil.xrm-ms
cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-ul.xrm-ms
cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\client-issuance-ul-oob.xrm-ms
cscript "%OfficePath%\Office16\ospp.vbs" /inslic:"%OfficePath%\root\Licenses16\pkeyconfig-office.xrm-ms`

I had to convert Visio and Project to MAK and it worked by executing this part only:

`cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\ProjectProVL_MAK_Client-ppd.xrm-ms"
cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\ProjectProVL_MAK_Client-ul-oob.xrm-ms"
cscript slmgr.vbs /ilc "%OfficePath%\root\Licenses16\ProjectProVL_MAK_Client-ul.xrm-ms`

Just want to make sure I won't run into problems in the future.

Thanks

**Comment by C0rn3j** [comment] 2023-10-23 11:44
Wanted to do the same Retail to VL conversion on Office 2021, found this repo that does it https://github.com/abbodi1406/C2R-R2V-AIO

Afterwards vlmcsd works fine.
